In [1]:
import pandas as pd

In [5]:
data=[['deep',21],['bhavna',22],['sachin',19],['kushwah',20]]

In [6]:
data

[['deep', 21], ['bhavna', 22], ['sachin', 19], ['kushwah', 20]]

In [15]:
s=pd.DataFrame(data,columns=['Name',"Age"])

In [16]:
s

      Name  Age
0     deep   21
1   bhavna   22
2   sachin   19
3  kushwah   20

In [17]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
s.index=['a','b','c','d']

In [20]:
print(s)

      Name  Age
a     deep   21
b   bhavna   22
c   sachin   19
d  kushwah   20

In [21]:
data2={"A":[1,2,3,4,5,6],"B":[2,4,5,67,89,6]}

In [22]:
data2

{'A': [1, 2, 3, 4, 5, 6], 'B': [2, 4, 5, 67, 89, 6]}

In [26]:
df=pd.DataFrame(data2)

In [27]:
df

   A   B
0  1   2
1  2   4
2  3   5
3  4  67
4  5  89
5  6   6

In [28]:
import numpy as np

In [31]:
arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"],index=['a','b'])

In [32]:
df

   A  B
a  1  2
b  3  4

In [33]:
pd.read_excel("data.xlsx")

       Name School  Marks
0      Deep    dpl     96
1    Bhavna    bpl     92
2    sachin   splv     87
3    raghav    rpl     45
4       raj   rpls     85
5     mohit    mpl     23
6     rohit  rplss     14
7     shyam   spls     57
8    deepka   dpls     86
9    deepak  dplss     35
10    raghu    gpl     86
11    jittu    jpl     84
12     aaka    apl     75
13     pole    ppl     68
14  kamlesh    kpl     69
15    sunil    vpl     48
16     maya   mpls     82
17    neelm   npls     83
18   shivan  lllpl     81

In [40]:
df=pd.read_json("data.json")

In [41]:
df

          name  age
0  Deepchandra   21
1       Bhavna   22

In [42]:
df=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [43]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [44]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [45]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [47]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [49]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [50]:
df.shape

(149, 5)