In [1]:
import pandas as pd

In [3]:
s=pd.Series({
    "Sachin" : 18426,

    "Virat" : 14085,
    
    "Rohit" : 11168,
    
    "Dhoni" : 10773,
    
    "Gill" : 2750
})
s

Sachin    18426
Virat     14085
Rohit     11168
Dhoni     10773
Gill       2750
dtype: int64

In [4]:
type(s)

pandas.core.series.Series

In [5]:
print(s.dtype)
print(s.shape)
print(s.size)
print(s.index)
print(s.values)
print(s.ndim)

int64
(5,)
5
Index(['Sachin', 'Virat', 'Rohit', 'Dhoni', 'Gill'], dtype='object')
[18426 14085 11168 10773  2750]
1

In [8]:
print(s.sort_values())
print(s.sort_values(ascending=False))

Gill       2750
Dhoni     10773
Rohit     11168
Virat     14085
Sachin    18426
dtype: int64
Sachin    18426
Virat     14085
Rohit     11168
Dhoni     10773
Gill       2750
dtype: int64

In [9]:
s = pd.Series([12,45,18,67,34,89,23,56,78,90])

In [16]:
# Print the first 5 elements.
# Print the last 3 elements.
# Print all values greater than 50.

print(s.head())
print(s.tail())
print(s[s>50])

0    12
1    45
2    18
3    67
4    34
dtype: int64
5    89
6    23
7    56
8    78
9    90
dtype: int64
3    67
5    89
7    56
8    78
9    90
dtype: int64

In [23]:
# Find the top 3 largest values.
# Find the bottom 2 smallest values.
print(s.nlargest(3))
print(s.nsmallest(3))

9    90
5    89
8    78
dtype: int64
0    12
2    18
6    23
dtype: int64

In [24]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [22, 25, 23],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age    City
0    Alice   22   Delhi
1      Bob   25  Mumbai
2  Charlie   23    Pune

In [31]:
print(df.index)
print(df.shape)
print(df.columns)
print(type(df))
print(df.columns.tolist())
print(df.dtypes)
print(df.info())
print(df.describe())

RangeIndex(start=0, stop=3, step=1)
(3, 3)
Index(['Name', 'Age', 'City'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
['Name', 'Age', 'City']
Name    object
Age      int64
City    object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
             Age
count   3.000000
mean   23.333333
std     1.527525
min    22.000000
25%    22.500000
50%    23.000000
75%    24.000000
max    25.000000

In [32]:
df["Salary"] = [50000,60000,70000]

In [33]:
df

      Name  Age    City  Salary
0    Alice   22   Delhi   50000
1      Bob   25  Mumbai   60000
2  Charlie   23    Pune   70000

In [34]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Alice","Bob","Charlie","David","Eva"],
    "Age":[22,25,23,26,24],
    "Marks":[85,78,92,88,95],
    "City":["Delhi","Mumbai","Pune","Delhi","Jaipur"]
})

In [35]:
df

      Name  Age  Marks    City
0    Alice   22     85   Delhi
1      Bob   25     78  Mumbai
2  Charlie   23     92    Pune
3    David   26     88   Delhi
4      Eva   24     95  Jaipur

In [37]:
# Print only the Name column.
# Print Name and Marks.

print(df["Name"])
print(df[["Name","Marks"]])

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object
      Name  Marks
0    Alice     85
1      Bob     78
2  Charlie     92
3    David     88
4      Eva     95

In [39]:
# Add a new column named Grade.
# Delete the City column.
df["Grade"]=["A","B","C","D","E"]
df=df.drop("City",axis=1)
print(df)

      Name  Age  Marks Grade
0    Alice   22     85     A
1      Bob   25     78     B
2  Charlie   23     92     C
3    David   26     88     D
4      Eva   24     95     E

In [62]:
import pandas as pd

df = pd.DataFrame({
    "Name":["Alice","Bob","Charlie","David","Eva"],
    "Age":[22,25,23,26,24],
    "Marks":[85,78,92,88,95],
    "City":["Delhi","Mumbai","Pune","Delhi","Jaipur"]
})

In [44]:
df["Name"]
df[["Name","Age"]]

      Name  Age
0    Alice   22
1      Bob   25
2  Charlie   23
3    David   26
4      Eva   24

In [52]:
print(df.loc[0])
print(df.iloc[0])
print(df.loc[1])
print(df.iloc[1])
print(df.at[0,"Name"])
print(df.iat[0,0])

Name     Alice
Age         22
Marks       85
City     Delhi
Name: 0, dtype: object
Name     Alice
Age         22
Marks       85
City     Delhi
Name: 0, dtype: object
Name        Bob
Age          25
Marks        78
City     Mumbai
Name: 1, dtype: object
Name        Bob
Age          25
Marks        78
City     Mumbai
Name: 1, dtype: object
Alice
Alice

In [63]:
df.isnull()

    Name    Age  Marks   City
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [54]:
df.query(" Age > 24 and City=='Mumbai'")

  Name  Age  Marks    City
1  Bob   25     78  Mumbai

In [57]:
print(df[df["Age"].between(23,28)])

      Name  Age  Marks    City
1      Bob   25     78  Mumbai
2  Charlie   23     92    Pune
3    David   26     88   Delhi
4      Eva   24     95  Jaipur

In [58]:
print(df[df["City"].isin(["Delhi","Pune"])])

      Name  Age  Marks   City
0    Alice   22     85  Delhi
2  Charlie   23     92   Pune
3    David   26     88  Delhi

In [64]:
df.isnull()
df.isnull().sum()

Name     0
Age      0
Marks    0
City     0
dtype: int64

In [65]:
import pandas as pd
df = pd.DataFrame({ 
    "Name": [ "Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry", "Ivy", "Jack", "Kevin", "Lily", "Mason", "Nina", "Oscar" ], 
    "Age": [ 22, 25, 23, 26, 24, 27, 21, 28, 22, 25, 29, 20, 24, 23, 26 ], 
    "Marks": [ 85, 78, 92, 88, 95, 67, 81, 90, 73, 84, 96, 76, 89, 91, 82 ], 
    "City": [ "Delhi", "Mumbai", "Pune", "Delhi", "Jaipur", "Mumbai", "Delhi", "Pune", "Bhopal", "Indore", "Jaipur", "Delhi", "Indore", "Bhopal", "Pune" ] }) 
print(df)

       Name  Age  Marks    City
0     Alice   22     85   Delhi
1       Bob   25     78  Mumbai
2   Charlie   23     92    Pune
3     David   26     88   Delhi
4       Eva   24     95  Jaipur
5     Frank   27     67  Mumbai
6     Grace   21     81   Delhi
7     Henry   28     90    Pune
8       Ivy   22     73  Bhopal
9      Jack   25     84  Indore
10    Kevin   29     96  Jaipur
11     Lily   20     76   Delhi
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal
14    Oscar   26     82    Pune

In [66]:
# Show students whose Marks are greater than 80.
# Show students whose Age is less than 25.
print(df.query("Marks > 80"))
print("------------")
print(df.query("Age<25"))

       Name  Age  Marks    City
0     Alice   22     85   Delhi
2   Charlie   23     92    Pune
3     David   26     88   Delhi
4       Eva   24     95  Jaipur
6     Grace   21     81   Delhi
7     Henry   28     90    Pune
9      Jack   25     84  Indore
10    Kevin   29     96  Jaipur
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal
14    Oscar   26     82    Pune
------------
       Name  Age  Marks    City
0     Alice   22     85   Delhi
2   Charlie   23     92    Pune
4       Eva   24     95  Jaipur
6     Grace   21     81   Delhi
8       Ivy   22     73  Bhopal
11     Lily   20     76   Delhi
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal

In [67]:
# Show students from Delhi.
# Show students whose Marks are between 80 and 90.
print(df.query("City == 'Delhi'"))
print("----------")
print(df[df["Marks"].between(80,90)])

     Name  Age  Marks   City
0   Alice   22     85  Delhi
3   David   26     88  Delhi
6   Grace   21     81  Delhi
11   Lily   20     76  Delhi
----------
     Name  Age  Marks    City
0   Alice   22     85   Delhi
3   David   26     88   Delhi
6   Grace   21     81   Delhi
7   Henry   28     90    Pune
9    Jack   25     84  Indore
12  Mason   24     89  Indore
14  Oscar   26     82    Pune

In [69]:
# Show students whose Age is greater than 22 and Marks are greater than 85.
# Show students whose City is not Mumbai.
print(df.query("Age > 22 and Marks > 85"))
print("----------")
print(df.query("City != 'Mumbai'"))

       Name  Age  Marks    City
2   Charlie   23     92    Pune
3     David   26     88   Delhi
4       Eva   24     95  Jaipur
7     Henry   28     90    Pune
10    Kevin   29     96  Jaipur
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal
----------
       Name  Age  Marks    City
0     Alice   22     85   Delhi
2   Charlie   23     92    Pune
3     David   26     88   Delhi
4       Eva   24     95  Jaipur
6     Grace   21     81   Delhi
7     Henry   28     90    Pune
8       Ivy   22     73  Bhopal
9      Jack   25     84  Indore
10    Kevin   29     96  Jaipur
11     Lily   20     76   Delhi
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal
14    Oscar   26     82    Pune

In [73]:
# Show students whose Name starts with "D".
# Show students whose Name contains the letter "a".
print(df[df["Name"].str.startswith("D")])
print("----------")
print(df[df["Name"].str.contains("a")])

    Name  Age  Marks   City
3  David   26     88  Delhi
----------
       Name  Age  Marks    City
2   Charlie   23     92    Pune
3     David   26     88   Delhi
4       Eva   24     95  Jaipur
5     Frank   27     67  Mumbai
6     Grace   21     81   Delhi
9      Jack   25     84  Indore
12    Mason   24     89  Indore
13     Nina   23     91  Bhopal
14    Oscar   26     82    Pune

In [74]:
df["Age Group"]=df["Age"].apply(lambda x : "Adult" if x>22 else "Minor")

In [75]:
df

       Name  Age  Marks    City Age Group
0     Alice   22     85   Delhi     Minor
1       Bob   25     78  Mumbai     Adult
2   Charlie   23     92    Pune     Adult
3     David   26     88   Delhi     Adult
4       Eva   24     95  Jaipur     Adult
5     Frank   27     67  Mumbai     Adult
6     Grace   21     81   Delhi     Minor
7     Henry   28     90    Pune     Adult
8       Ivy   22     73  Bhopal     Minor
9      Jack   25     84  Indore     Adult
10    Kevin   29     96  Jaipur     Adult
11     Lily   20     76   Delhi     Minor
12    Mason   24     89  Indore     Adult
13     Nina   23     91  Bhopal     Adult
14    Oscar   26     82    Pune     Adult

In [78]:
# Sort by Marks ascending.
# Sort by Marks descending.
# Sort by City then Marks.
# Find top 5 scorers.
# Find youngest 3 students.
print(df.sort_values("Marks"))
print("-----")
print(df.sort_values("Marks",ascending=False))
print("-----")
print(df.sort_values(["City","Marks"]))
print("-----")
print(df.sort_index())
print("-----")
print(df.nlargest(5,"Marks"))
print("-----")
print(df.nlargest(3,"Age"))

       Name  Age  Marks    City Age Group
5     Frank   27     67  Mumbai     Adult
8       Ivy   22     73  Bhopal     Minor
11     Lily   20     76   Delhi     Minor
1       Bob   25     78  Mumbai     Adult
6     Grace   21     81   Delhi     Minor
14    Oscar   26     82    Pune     Adult
9      Jack   25     84  Indore     Adult
0     Alice   22     85   Delhi     Minor
3     David   26     88   Delhi     Adult
12    Mason   24     89  Indore     Adult
7     Henry   28     90    Pune     Adult
13     Nina   23     91  Bhopal     Adult
2   Charlie   23     92    Pune     Adult
4       Eva   24     95  Jaipur     Adult
10    Kevin   29     96  Jaipur     Adult
-----
       Name  Age  Marks    City Age Group
10    Kevin   29     96  Jaipur     Adult
4       Eva   24     95  Jaipur     Adult
2   Charlie   23     92    Pune     Adult
13     Nina   23     91  Bhopal     Adult
7     Henry   28     90    Pune     Adult
12    Mason   24     89  Indore     Adult
3     David   26     88   Delhi     Adult
0     Alice   22     85   Delhi     Minor
9      Jack   25     84  Indore     Adult
14    Oscar   26     82    Pune     Adult
6     Grace   21     81   Delhi     Minor
1       Bob   25     78  Mumbai     Adult
11     Lily   20     76   Delhi     Minor
8       Ivy   22     73  Bhopal     Minor
5     Frank   27     67  Mumbai     Adult
-----
       Name  Age  Marks    City Age Group
8       Ivy   22     73  Bhopal     Minor
13     Nina   23     91  Bhopal     Adult
11     Lily   20     76   Delhi     Minor
6     Grace   21     81   Delhi     Minor
0     Alice   22     85   Delhi     Minor
3     David   26     88   Delhi     Adult
9      Jack   25     84  Indore     Adult
12    Mason   24     89  Indore     Adult
4       Eva   24     95  Jaipur     Adult
10    Kevin   29     96  Jaipur     Adult
5     Frank   27     67  Mumbai     Adult
1       Bob   25     78  Mumbai     Adult
14    Oscar   26     82    Pune     Adult
7     Henry   28     90    Pune     Adult
2   Charlie   23     92    Pune     Adult
-----
       Name  Age  Marks    City Age Group
0     Alice   22     85   Delhi     Minor
1       Bob   25     78  Mumbai     Adult
2   Charlie   23     92    Pune     Adult
3     David   26     88   Delhi     Adult
4       Eva   24     95  Jaipur     Adult
5     Frank   27     67  Mumbai     Adult
6     Grace   21     81   Delhi     Minor
7     Henry   28     90    Pune     Adult
8       Ivy   22     73  Bhopal     Minor
9      Jack   25     84  Indore     Adult
10    Kevin   29     96  Jaipur     Adult
11     Lily   20     76   Delhi     Minor
12    Mason   24     89  Indore     Adult
13     Nina   23     91  Bhopal     Adult
14    Oscar   26     82    Pune     Adult
-----
       Name  Age  Marks    City Age Group
10    Kevin   29     96  Jaipur     Adult
4       Eva   24     95  Jaipur     Adult
2   Charlie   23     92    Pune     Adult
13     Nina   23     91  Bhopal     Adult
7     Henry   28     90    Pune     Adult
-----
     Name  Age  Marks    City Age Group
10  Kevin   29     96  Jaipur     Adult
7   Henry   28     90    Pune     Adult
5   Frank   27     67  Mumbai     Adult

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Employee":["Amit","Priya","Rahul","Sara","Mohit","Neha","Karan","Pooja"], 
    "Department":["IT","HR","IT","HR","Sales","Sales","IT","HR"], 
    "Salary":[50000,45000,60000,48000,55000,58000,65000,47000], 
    "Sales":[100,80,120,90,150,140,130,85], 
    "Experience":[2,3,5,4,6,5,7,2] 
})
print(df)

  Employee Department  Salary  Sales  Experience
0     Amit         IT   50000    100           2
1    Priya         HR   45000     80           3
2    Rahul         IT   60000    120           5
3     Sara         HR   48000     90           4
4    Mohit      Sales   55000    150           6
5     Neha      Sales   58000    140           5
6    Karan         IT   65000    130           7
7    Pooja         HR   47000     85           2

In [2]:
print(df.groupby("Department")) # ye kuch bhi output nahi dega

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002819DAF2E40>

In [4]:
print(df.groupby("Department")["Salary"])#ye bhi kuch nahi dega output me

<pandas.core.groupby.generic.SeriesGroupBy object at 0x000002819DB71090>

In [9]:
# bina aggregrate ke ham groupby use nahi ker sakte 
print(df.groupby("Department")["Salary"].mean())

Department
HR       46666.666667
IT       58333.333333
Sales    56500.000000
Name: Salary, dtype: float64

In [18]:
print(df.groupby("Department")["Salary"].sum())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Salary"].min())
print(df.groupby("Department")["Salary"].count())

Department
HR       140000
IT       175000
Sales    113000
Name: Salary, dtype: int64
Department
HR       48000
IT       65000
Sales    58000
Name: Salary, dtype: int64
Department
HR       45000
IT       50000
Sales    55000
Name: Salary, dtype: int64
Department
HR       3
IT       3
Sales    2
Name: Salary, dtype: int64

In [19]:
print(df.groupby(["Department","Sales"])["Salary"].sum())

Department  Sales
HR          80       45000
            85       47000
            90       48000
IT          100      50000
            120      60000
            130      65000
Sales       140      58000
            150      55000
Name: Salary, dtype: int64

In [20]:
print(df.groupby("Department")["Salary"].agg(["mean","sum","max","min","count"]))

                    mean     sum    max    min  count
Department
HR          46666.666667  140000  48000  45000      3
IT          58333.333333  175000  65000  50000      3
Sales       56500.000000  113000  58000  55000      2

In [22]:
res=df.groupby("Department")["Salary"].agg(
    score_mean="mean",
    score_sum="sum",
    score_max="max", 
)
print(res)

              score_mean  score_sum  score_max
Department
HR          46666.666667     140000      48000
IT          58333.333333     175000      65000
Sales       56500.000000     113000      58000

In [25]:
groups=df.groupby("Department")
groups.get_group("HR")
groups.get_group("IT")

  Employee Department  Salary  Sales  Experience
0     Amit         IT   50000    100           2
2    Rahul         IT   60000    120           5
6    Karan         IT   65000    130           7

In [26]:
import pandas as pd 
employees = pd.DataFrame({
    "Emp_ID":[101,102,103,104,105], 
    "Name":["Amit","Priya","Rahul","Sara","Neha"], 
    "Department":["IT","HR","IT","Sales","HR"] }) 
print(employees)

   Emp_ID   Name Department
0     101   Amit         IT
1     102  Priya         HR
2     103  Rahul         IT
3     104   Sara      Sales
4     105   Neha         HR

In [27]:
salary = pd.DataFrame({
    "Emp_ID":[101,102,103,106], 
    "Salary":[50000,45000,60000,70000] }) 
print(salary)

   Emp_ID  Salary
0     101   50000
1     102   45000
2     103   60000
3     106   70000

In [29]:
pd.merge(employees,salary,on="Emp_ID")

   Emp_ID   Name Department  Salary
0     101   Amit         IT   50000
1     102  Priya         HR   45000
2     103  Rahul         IT   60000

In [30]:
pd.merge(employees,salary,on="Emp_ID",how="left")

   Emp_ID   Name Department   Salary
0     101   Amit         IT  50000.0
1     102  Priya         HR  45000.0
2     103  Rahul         IT  60000.0
3     104   Sara      Sales      NaN
4     105   Neha         HR      NaN

In [31]:
pd.merge(employees,salary,on="Emp_ID",how="right")

   Emp_ID   Name Department  Salary
0     101   Amit         IT   50000
1     102  Priya         HR   45000
2     103  Rahul         IT   60000
3     106    NaN        NaN   70000

In [32]:
pd.merge(employees,salary,on="Emp_ID",how="outer")

   Emp_ID   Name Department   Salary
0     101   Amit         IT  50000.0
1     102  Priya         HR  45000.0
2     103  Rahul         IT  60000.0
3     104   Sara      Sales      NaN
4     105   Neha         HR      NaN
5     106    NaN        NaN  70000.0

In [33]:
df1=pd.DataFrame({"Name":["Deep","Sachin"]})
df2=pd.DataFrame({"Name":["Deepak","Rahul"]})
pd.concat([df1,df2])

     Name
0    Deep
1  Sachin
0  Deepak
1   Rahul

In [34]:
pd.concat([df1,df2], axis=1)

     Name    Name
0    Deep  Deepak
1  Sachin   Rahul